In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [64]:
train=pd.read_csv('/kaggle/input/titanic/train.csv')

print("Data Values Sucessfully Grabbed")
print("Number of values in Train",len(train))

Values Sucessfully Grabbed
Number of values in Train 891
Number of values in Test 418


In [65]:
print("Train Keys",train.keys())
print('*'*100)


Train Keys Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
****************************************************************************************************
Test Keys Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [66]:
train.head() # the data provided to us for training our Model

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [69]:
X = train.iloc[:,[2,5]].values # starting from  0 is PassengerId , Pclass is 2 and Age is 5 
y = train.iloc[:,1].values # Survived is 1 - which need to be predicted by our model

In [84]:
X # dont get scared - all this is easy

array([[ 3.        , 22.        ],
       [ 1.        , 38.        ],
       [ 3.        , 26.        ],
       ...,
       [ 3.        , 29.69911765],
       [ 1.        , 26.        ],
       [ 3.        , 32.        ]])

In [86]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

### The X is having missing values but there is no missing value in y 
### So, have to work on y? No. We have to work on X

#### 1. Delete the values that are unknown 
#### 2. Fill the values to anything 
#### 3. Fill it with Mean, Mode and third one is Median 



In [90]:
print("The dimesions of X is ", len(X),len(X[0]))
print("The dimesions of y is ", y.shape)

The dimesions of X is  891 2
The dimesions of y is  (891,)


### As a number of values are found to be NaN - that means ;;;; you guessed it right Not a Number - Lets remove them

In [80]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
X = my_imputer.fit_transform(X)
# all Unknown or so called Not a number values 

In [57]:
# Hey Pythoners !! you guessed it right. You can also use this to replace the values.
# I have created this especially for you 
"""
for x in range(len(X)):
    if np.isnan(X[x][1]):
        X[x][1]=20
"""
# Feel free to use this too 

In [91]:
X # see it is easy

array([[ 3.        , 22.        ],
       [ 1.        , 38.        ],
       [ 3.        , 26.        ],
       ...,
       [ 3.        , 29.69911765],
       [ 1.        , 26.        ],
       [ 3.        , 32.        ]])

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [94]:
print("The dimesions of X_train is ", len(X_train),len(X_train[0]))
print("The dimesions of X_test is ", len(X_test),len(X_test[0]))

print("The dimesions of y_train is ", y_train.shape)
print("The dimesions of y_test is ", y_test.shape)

The dimesions of X_train is  712 2
The dimesions of X_test is  179 2
The dimesions of y_train is  (712,)
The dimesions of y_test is  (179,)


In [95]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)

In [96]:
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [97]:
# X_test = test.iloc[:,[1,4]]
# y_test=test.iloc[:,1]

y_pred = classifier.predict(X_test)

In [99]:
print("The dimesions of y_pred is ", y_pred.shape)
print("The dimesions of y_test is ", y_test.shape)

The dimesions of y_pred is  (179,)
The dimesions of y_test is  (179,)


In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

![Image](https://media.geeksforgeeks.org/wp-content/uploads/Confusion_Matrix6.png)


In [103]:
cm

array([[97, 13],
       [33, 36]])

# Lets create a submission for Kaggle

In [105]:
test=pd.read_csv('/kaggle/input/titanic/test.csv')
print("Number of values in Test",len(test))
print("Test Keys",test.keys())

Number of values in Test 418
Test Keys Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [115]:
test.head() # This is the data on which we have to make the submission after prediction

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [109]:
submission_X = test.iloc[:,[1,4]].values # starting from  0 is PassengerId , Pclass is 1 and Age is 4 

In [110]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
submission_X = my_imputer.fit_transform(submission_X)

In [111]:
submission_pred = classifier.predict(submission_X)

In [112]:
submission=pd.DataFrame({
        'PassengerID':test['PassengerId'],
        "Survived":submission_pred
        })

In [113]:
submission

PassengerID  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [114]:
submission.to_csv('submission.csv', index=False)

In [ ]:
67% accuracy

Currently, in this case we considered only Age and Class of the passenger. which gave us 67% correct prediction about the person to survive or not


We can add more factors in consideration like the Gender, Age, Sibling or Spouse and many more to increase the result of our predcition.

Note down the things for future use in this project
If you know the terms then can easily work on it faster

* Hot Encoder
* One Hot Encoder
* Label Encoding
* Imputer
* Confusion Matrix
* Accuracy
* Recall
* Precision
* F measure
* True Positive 
* True Negative

Train your model with more than this accuracy and mail me the results.
It would be nice to see better results coming.

If you stuck somewhere - google it - google it more - and again google it
If still stuck then mail me with the code and the error logs 
I would love to google it. :P




In [ ]:
test.head